name: Android Build

on:
  push:
    branches:
      - master

env:
  SIGN_STORE_FILE: "${{ github.workspace }}/keystore.jks"
  SIGN_STORE_PASSWORD: ${{ secrets.SIGN_STORE_PASSWORD }}
  SIGN_KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
  SIGN_KEY_PASSWORD: ${{ secrets.SIGN_KEY_PASSWORD }}

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Create Keystore File
      run: echo "${{ secrets.SIGN_STORE_BASE64 }}" | base64 --decode > "$SIGN_STORE_FILE"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew assembleRelease -PsignStoreFile="$SIGN_STORE_FILE" \
          -PsignStorePassword="$SIGN_STORE_PASSWORD" \
          -PsignKeyAlias="$SIGN_KEY_ALIAS" \
          -PsignKeyPassword="$SIGN_KEY_PASSWORD"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: app/build/outputs/apk/release/app-release.apk
